source-file /home/sj/dotfiles-sj/tmuxModule/customBingdings.conf
source-file /home/sj/dotfiles-sj/tmuxModule/sessionWindowPane/pane.conf
source-file /home/sj/dotfiles-sj/tmuxModule/sessionWindowPane/session.conf
source-file /home/sj/dotfiles-sj/tmuxModule/sessionWindowPane/window.conf
source-file /home/sj/dotfiles-sj/tmuxModule/mernWeb/mernWeb.conf
source-file /home/sj/dotfiles-sj/tmuxModule/settings.conf
source-file /home/sj/dotfiles-sj/tmuxModule/browser/browser.conf
source-file /home/sj/dotfiles-sj/tmuxModule/gitGithub/gitGithub.conf
source-file /home/sj/dotfiles-sj/tmuxModule/mernWeb/npmScript/npmScript.conf
source-file /home/sj/dotfiles-sj/tmuxModule/tmuxZshCli/tmuxZshCli.conf
