# for repeatiting chord keys commands
bind-key n switch-client -T prefix_n
# Exit prefix_s mode with q or Escape (or any key you like)
bind-key -T prefix_n q switch-client -T root
bind-key -T prefix_n Escape switch-client -T root

# Running bun dev command in tmux pane 3
bind-key -T prefix_n d run-shell 'tmux send-keys -t :.3 "bun dev" C-m'

# Running bun postinstall (generate prisma) command in tmux pane 3
bind-key -T prefix_n p run-shell 'tmux send-keys -t :.2 "bun postinstall" C-m'

# Running bun postinstall (generate prisma) command in tmux pane 3
bind-key -T prefix_n w run-shell 'tmux send-keys -t :.2 "bun watch" C-m'





# send  C-c (for exit any process) to default pane 3  or other pane by input prompt
bind q command-prompt -p "Pane number (default 3)" "run-shell '/home/sj/dotfiles-sj/tmuxModule/tmuxShellScript/tmux_send_c_c.sh %%'"



