# for repeatiting chord keys commands
bind-key u switch-client -T prefix_u
# Exit prefix_u mode with q or Escape (or any key you like)
bind-key -T prefix_u q switch-client -T root
bind-key -T prefix_u Escape switch-client -T root

# Prefix, u, c : copy current pane pwd and cd into target pane
bind-key -r -T prefix_u c run-shell "/home/sj/dotfiles-sj/tmuxModule/tmuxZshCli/shellscript/cd_pane_sync.sh"
# kill all panse except first 3
bind-key -r -T prefix_u k run-shell "/home/sj/dotfiles-sj/tmuxModule/tmuxZshCli/shellscript/cd_pane_sync.sh"


